# Generated by Django 4.2.4 on 2023-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post\\beda6c40b85346c986b27d27a284ebaa.jpg'),
        ),
    ]
