# Generated by Django 4.2.2 on 2023-11-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='Nuevo evento', help_text='Titulo del evento', max_length=155),
            preserve_default=False,
        ),
    ]
