# Generated by Django 4.2.4 on 2023-11-04 18:52

import SportBlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportBlog', '0002_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=SportBlog.models.nombreImagen),
        ),
    ]
