# Generated by Django 4.2.4 on 2023-11-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportBlog', '0004_relation_likes_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
    ]
